# Generated by Django 3.2 on 2021-08-23 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps_gdocumental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_alta', models.DateField(blank=True, null=True, verbose_name='Fecha alta')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción Sector')),
                ('tipo_suelo', models.CharField(max_length=15, verbose_name='Tipo Suelo')),
                ('sector', models.CharField(max_length=15, verbose_name='Sector')),
                ('zona', models.CharField(max_length=15, verbose_name='Zona')),
                ('grado_edificabilidad', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, verbose_name='Grado Edificabilidad')),
                ('ocupacion_maxima', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, verbose_name='Ocupación Máxima')),
                ('coeficiente_reduccion', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Coeficiente Reducción')),
                ('edificacion', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Edificabilidad')),
                ('altura_maxima', models.CharField(blank=True, max_length=25, verbose_name='Altura maxima edificación')),
                ('planta_sotano', models.BooleanField(verbose_name='Planta sotano')),
                ('condiciones_uso', models.CharField(blank=True, max_length=25, verbose_name='Condiciones Uso')),
                ('observaciones', models.TextField(blank=True, max_length=500, verbose_name='Observaciones')),
                ('usuario_crea', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifica', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sector',
            },
        ),
        migrations.CreateModel(
            name='Pgou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_alta', models.DateField(blank=True, null=True, verbose_name='Fecha alta')),
                ('descripcion', models.CharField(max_length=50, null=True, verbose_name='PGOU')),
                ('unidad', models.CharField(blank=True, max_length=15, verbose_name='Unidad')),
                ('tipo', models.CharField(blank=True, max_length=15, verbose_name='Tipo')),
                ('pk_gestion_documental', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_gdocumental.gdocumental', verbose_name='Adjuntar Fichero')),
                ('pk_sector', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_pgou.sector', verbose_name='Sector')),
                ('usuario_crea', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifica', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PGOU',
            },
        ),
    ]
