# Generated by Django 3.2 on 2021-08-23 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_empresas', '0001_initial'),
        ('apps_pgou', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps_gdocumental', '0001_initial'),
        ('apps_ibi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='Clasificacion del inmueble')),
                ('usuario_crea', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifica', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clasificacion',
            },
        ),
        migrations.CreateModel(
            name='RegistroPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('numero_finca_registral', models.CharField(max_length=50, null=True, unique=True, verbose_name='Número finca registral')),
                ('descripcion_registro', models.CharField(max_length=50, verbose_name='Descripcion Registro')),
                ('observacion_registro', models.TextField(blank=True, max_length=500, verbose_name='Observaciones')),
                ('pk_gestion_documental', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_gdocumental.gdocumental', verbose_name='Adjuntar Fichero')),
                ('usuario_crea', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifica', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Registro Propiedad',
            },
        ),
        migrations.CreateModel(
            name='TipoFinca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='Clasificacion del inmueble')),
                ('usuario_crea', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifica', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tipo de Finca',
            },
        ),
        migrations.CreateModel(
            name='Tasacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción Tasación')),
                ('fecha_tasacion', models.DateField(verbose_name='Fecha tasación')),
                ('importe_tasacion', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Importe tasación')),
                ('pk_gestion_documental', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_gdocumental.gdocumental', verbose_name='Adjuntar Fichero')),
                ('usuario_crea', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifica', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tasaciones',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_alta', models.DateField(verbose_name='Fecha alta')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha baja')),
                ('cliente_venta', models.CharField(blank=True, max_length=25, verbose_name='Cliente Venta')),
                ('importe_venta', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Importe Venta')),
                ('parcela', models.CharField(blank=True, max_length=15, unique=True, verbose_name='Parcela')),
                ('numero_nuevo', models.CharField(blank=True, max_length=15, verbose_name='Numero parcela interno')),
                ('metros_cuadrados', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Metros cuadrados')),
                ('cabida', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Cabida')),
                ('cuenta_terreno', models.CharField(blank=True, choices=[('', ''), ('220', '220'), ('230', '230'), ('310', '310')], default='220', max_length=6, verbose_name='Cuenta contable terreno')),
                ('importe_contable_suelo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Valor contable terreno ')),
                ('cuenta_construccion', models.CharField(blank=True, choices=[('', ''), ('220', '220'), ('230', '230'), ('310', '310')], default='230', max_length=6, verbose_name='Cuenta contable construccion')),
                ('importe_contable_construccion', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Valor contable construccion')),
                ('observaciones', models.TextField(blank=True, max_length=800, verbose_name='Observaciones')),
                ('pk_clasificacion', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_stock.clasificacion', verbose_name='Clasificacion')),
                ('pk_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_empresas.empresa', verbose_name='Empresa')),
                ('pk_ibi', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_ibi.ibi', verbose_name='Ibi')),
                ('pk_pgou', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_pgou.pgou', verbose_name='PGOU')),
                ('pk_registro', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_stock.registropropiedad', verbose_name='Nº de Finca')),
                ('pk_tasacion', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_stock.tasacion', verbose_name='Imforme de Tasación')),
                ('pk_tipoFinca', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_stock.tipofinca', verbose_name='Tipo Finca')),
                ('usuario_crea', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifica', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stock',
            },
        ),
        migrations.CreateModel(
            name='Segregaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_segregacion', models.DateField(verbose_name='Fecha segregación')),
                ('parcela_segregada', models.CharField(blank=True, max_length=15, unique=True, verbose_name='Parcela Segregada')),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='Segregaciones')),
                ('observaciones', models.TextField(blank=True, max_length=800, verbose_name='Observaciones')),
                ('pk_stock', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_stock.stock', verbose_name='Finca Matriz')),
                ('usuario_crea', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifica', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Resumen Segregaciones ',
            },
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='Dsescripción Foto')),
                ('fichero_pdf', models.FileField(upload_to='./fotos', verbose_name='Adjuntar foto')),
                ('pk_stock', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_stock.stock', verbose_name='Adjuntar Foto')),
                ('usuario_crea', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifica', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fotos',
            },
        ),
    ]
