# Generated by Django 3.2 on 2021-08-23 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps_gdocumental', '0001_initial'),
        ('apps_empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_alta', models.DateField(blank=True, null=True, verbose_name='Fecha alta')),
                ('descripcion_catastral', models.CharField(max_length=50, verbose_name='Gestor del Catastro')),
                ('referencia_catastral', models.CharField(max_length=20, verbose_name='Referencia Catastral')),
                ('valor_suelo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Valor suelo')),
                ('valor_construccion', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Valor construccion')),
                ('valor_catastral', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Valor catastral')),
                ('metros2_suelo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Metros² suelo')),
                ('metros2_construido', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Metros² construidos')),
                ('link_catastro', models.CharField(blank=True, max_length=250, verbose_name='Link foto catastro')),
                ('link_googlemaps', models.CharField(blank=True, max_length=250, verbose_name='Coordenadas Google Maps')),
                ('pk_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_empresas.empresa', verbose_name='Empresa')),
                ('pk_gestion_documental', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_gdocumental.gdocumental', verbose_name='Fichero')),
                ('usuario_crea', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifica', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Catastro',
                'ordering': ['referencia_catastral'],
            },
        ),
    ]
