# Generated by Django 3.2 on 2021-08-23 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps_gdocumental', '0001_initial'),
        ('apps_empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='Descripción')),
                ('usuario_crea', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifica', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('grupo_cotizacion', models.CharField(max_length=2, verbose_name='Grupo Cotizacion')),
                ('dni', models.CharField(max_length=10, verbose_name='DNI')),
                ('seguidad_social', models.CharField(blank=True, max_length=14, verbose_name='Seguridad Social')),
                ('fecha_alta', models.DateField(verbose_name='Fecha alta')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha baja')),
                ('nombre', models.CharField(help_text='Nombre del trabajador', max_length=20, verbose_name='Nombre')),
                ('primer_apellido', models.CharField(blank=True, help_text='Primer apellido del trabajador', max_length=20, verbose_name='Primer apellido')),
                ('segundo_apellido', models.CharField(blank=True, help_text='Segundo apellido del trabajador', max_length=20, verbose_name='Segundo apellido')),
                ('estudios', models.CharField(blank=True, help_text='Estudios Máximos Alcanzados', max_length=50, verbose_name='Estudios realizados')),
                ('cuenta_corriente', models.CharField(blank=True, max_length=24, verbose_name='Cuenta Corriente')),
                ('foto', models.ImageField(blank=True, upload_to='./fotos', verbose_name='Adjuntar Foto')),
                ('direccion_empleado', models.CharField(blank=True, help_text='Dirección de residencia completa del trabajador', max_length=100, verbose_name='Dirección')),
                ('codigo_postal', models.CharField(blank=True, max_length=5, verbose_name='Código Postal')),
                ('telefono', models.CharField(blank=True, max_length=12, verbose_name='Telefono')),
                ('movil', models.CharField(blank=True, max_length=12, verbose_name='Móvil')),
                ('email', models.EmailField(blank=True, max_length=25, verbose_name='Email')),
                ('salario_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Salario Bruto Anual')),
                ('liquido_mes', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Salario Liquido Mes')),
                ('observacion', models.TextField(blank=True, max_length=600, verbose_name='Observaciones')),
                ('pk_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_trabajadores.categoria', verbose_name='Categoria laboral')),
                ('pk_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_empresas.empresa', verbose_name='Empresa')),
                ('pk_poblacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_empresas.poblacion', verbose_name='Población')),
                ('pk_provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_empresas.provincia', verbose_name='Provincia')),
                ('usuario_crea', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifica', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Trabajadores',
            },
        ),
        migrations.CreateModel(
            name='Vacaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField(blank=True)),
                ('dias', models.IntegerField(blank=True, default=0, verbose_name='Días')),
                ('pk_gestion_documental', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_gdocumental.gdocumental', verbose_name='Documento')),
                ('pk_vacaciones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_trabajadores.trabajador', verbose_name='Vacaciones')),
                ('usuario_crea', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifica', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vacaciones',
            },
        ),
    ]
