# Generated by Django 3.2 on 2021-08-23 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='Description porvincia')),
                ('usuario_crea', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifica', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='Poblacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='Description población')),
                ('usuario_crea', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifica', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Población',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('codigoempresa', models.CharField(max_length=4, unique=True, verbose_name='Código de Empresa')),
                ('descripcion', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la empresa')),
                ('nif', models.CharField(max_length=12, verbose_name='NIF')),
                ('numero_ss', models.CharField(max_length=14, verbose_name='Nº de la Seguridad Social')),
                ('fecha_creacion', models.DateField(blank=True, null=True, verbose_name='Fecha Creación')),
                ('fecha_liquidacion', models.DateField(blank=True, null=True, verbose_name='Fecha liquidacion')),
                ('forma_societaria', models.CharField(blank=True, max_length=25, verbose_name='Forma Societaria')),
                ('inscripcion', models.CharField(blank=True, max_length=50, verbose_name='Inscripción')),
                ('grupo_fiscal_IS', models.CharField(blank=True, max_length=50, verbose_name='Grupo Fiscal IS')),
                ('grupo_fiscal_IVA', models.CharField(blank=True, max_length=50, verbose_name='Grupo Fiscal IVA')),
                ('cnae', models.CharField(blank=True, max_length=500, verbose_name='CNAE')),
                ('direccion_social', models.CharField(blank=True, max_length=200, verbose_name='Dirección Social')),
                ('direccion_fiscal', models.CharField(blank=True, max_length=200, verbose_name='Dirección Fiscal')),
                ('codigoPostal', models.CharField(blank=True, max_length=5, verbose_name='Código Postal')),
                ('observacion', models.TextField(blank=True, max_length=500, verbose_name='Observaciones')),
                ('pk_poblacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_empresas.poblacion', verbose_name='Población')),
                ('pk_provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_empresas.provincia', verbose_name='Provincia')),
                ('usuario_crea', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifica', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
                'ordering': ['codigoempresa'],
            },
        ),
    ]
